export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_ALLUSER_REQUEST = "GET_ALLUSER_REQUEST";
export const GET_ALLUSER_SUCCESS = "GET_ALLUSER_SUCCESS";
export const GET_ALLUSER_ERROR = "GET_ALLUSER_ERROR";
